spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-13-236-183-251.ap-southeast-2.compute.amazonaws.com:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: blog_user
    password: Gaoyuan1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.korben.blog: debug
  file: log/blog-dev.log



